### ISSUE TITLE
test_cmds fails with python 3.3.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [micheles/plac#12]
```
What steps will reproduce the problem?
1. download plac-0.9.1.tar.gz from pypi
2. install to python 3.3.1 with 
    py -3.3 setup.py install 
(this is equivalent to c:\python33\python.exe setup.py install)

3. cd plac-0.9.1
   py -3.3 test_plac.py

What is the expected output?

A message telling all ok or no output at all

 What do you see instead?
D:\tmp\plac-0.9.1\doc>py -3 test_plac.py
Running test_batch
Running test_cmd_abbrevs
usage: test_plac.py {help,commit} ...
test_plac.py: error: No command 'foo'
Running test_cmds
Traceback (most recent call last):
  File "test_plac.py", line 230, in <module>
    maybegen = test()
  File "test_plac.py", line 184, in test_cmds
    expect(SystemExit, plac.call, cmds, [])
  File "test_plac.py", line 18, in expect
    func(*args, **kw)
  File "C:\Python33\lib\site-packages\plac-0.9.1-py3.3.egg\plac_core.py", line 3
09, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "C:\Python33\lib\site-packages\plac-0.9.1-py3.3.egg\plac_core.py", line 1
89, in consume
    args = [getattr(ns, a) for a in self.argspec.args]
AttributeError: 'ArgumentParser' object has no attribute 'argspec'


What version of the product are you using? On what operating system?
plac 0.9.1
On windows xp sp3

Please provide any additional information below.
Installing and testing to python 2.7 shows no error.

Running test_plac.py in py 3.3.1 with  pytest 2.3.5 tells that it is the only 
test failing in the file, (besides the one for sqlalchemy, which fails because 
the module is missing)

Additionally, deprecation warnings are seen for module imp. 

```

Original issue reported on code.google.com by `ccanepacc@gmail.com` on 9 May 2013 at 10:49

**Comment by micheles** [comment]
Fixed in 0.9.3
