### ISSUE TITLE
Cannot parse Python 3.5/3.6 typing annotations

### ISSUE THREAD

**Issue by rprechelt** [micheles/plac#23]
Following the examples in the documentation, 
```

def main(dirname):
    """ Do something with this directory. 
    """

if __name__ == "__main__":
    import plac; plac.call(main)
```

works correctly. but changing the definition to

    def main(dirname: str):

which is valid Python 3.5 (with `typing` package) or valid Python 3.6, results in 

```
Traceback (most recent call last):
  File "process.py", line 47, in <module>
    import plac; plac.call(main)
  File "/home/user/.local/lib/python3.6/site-packages/plac_core.py", line 324, in call
    parser = parser_from(obj)
  File "/home/user/.local/lib/python3.6/site-packages/plac_core.py", line 133, in parser_from
    parser.populate_from(obj)
  File "/home/user/.local/lib/python3.6/site-packages/plac_core.py", line 257, in populate_from
    a = Annotation.from_(ann)
  File "/home/user/.local/lib/python3.6/site-packages/plac_core.py", line 91, in from_
    return cls(*obj)
TypeError: type object argument after * must be an iterable, not type
```

**Comment by kirbyfan64** [comment]
Plac works based on the assumption that annotations on the main function are argument descriptions, so I'm not sure what you thought was going to happen...
